### ISSUE TITLE
Helm chart refers to invalid image tag

### ISSUE THREAD

**Issue by rjhenry** [ukfast/helm-charts#5]
The chart values refer to tag v1.0.1, but on the Docker hub there's only tags "latest" and "1.0.1" - this results in the Helm release failing as Kubernetes cannot pull the correct image.

**Comment by miff2000** [comment]
Hey @rjhenry 

Thanks for flagging this. We've been moving images from the the `ukfast` organisation to the merged `ans-group`/`ansgroup` one in GitHub and Docker Hub. I think this may have been a manual mistake made during that, but I'll get that checked to confirm.

Our usually naming convention is `/^v([0-9.]+)$/`, so if it was a mistake then we'll get the Docker Hub image updated to match and close the PR. Otherwise we'll get your PR merged.

Thanks again!

**Comment by 0x4c6565** [comment]
@rjhenry, apologies - the build tag pattern was incorrect in Docker Hub, which has now been corrected. I've pushed `v1.0.1`
